export enum ApiEndpoints {
	REGISTER = "/signup",
	LOGIN = "/client-api/internalAuth/login",
	BASICINFO = "/client-api/profile/basic-info",
	TIPUSER = "/stream/chat/rpc/tipUser",
	SETFEATURESTATE = "/client-api/admin/feature/setFeatureState",
	SETPROVIDERSTATE = "/client-api/admin/providers/saveExtProvidersList",
	GETPROVIDERS = "/client-api/admin/providers/getSlotsProviders",
	EDITUSERINFO = "/client-api/admin/user/editUserInfo",
	CREATEKOTH = "/client-api/admin/koth/createEvent",
	ENABLERAIN = "/stream/chat/rpc/startCustomRain",
	STOPCUSTOMRAIN = "/stream/chat/rpc/stopCustomRain",
	GETOPENRAINS = "/client-api/admin/rain/getOpenRains",
	GETLASTKOTHEVENTID = "/client-api/koth/getFirstKoth",
}
