export enum ApiEndpoints {
	REGISTER = "/signup",
	LOGIN = "/client-api/internalAuth/login",
	BASIC_INFO = "/client-api/profile/basic-info",
	TIP_USER = "/stream/chat/rpc/tipUser",
	SET_FEATURE_STATE = "/client-api/admin/feature/setFeatureState",
	SET_PROVIDER_STATE = "/client-api/admin/providers/saveExtProvidersList",
	GET_PROVIDERS = "/client-api/admin/providers/getSlotsProviders",
	EDIT_USER_INFO = "/client-api/admin/user/editUserInfo",
	CREATE_KOTH = "/client-api/admin/koth/createEvent",
	ENABLE_RAIN = "/stream/chat/rpc/startCustomRain",
	STOP_CUSTOM_RAIN = "/stream/chat/rpc/stopCustomRain",
	GET_OPEN_RAINS = "/client-api/admin/rain/getOpenRains",
	GET_LAST_KOTH_EVENT_ID = "/client-api/koth/getFirstKoth",
	GET_CURRENT_KOTH_EVENTS_BASIC_INFO = "/client-api/admin/koth/getCurrentEventBasicInfo",
	GET_CRYPTO_ADMIN_TRANSACTIONS = "/client-api/admin/crypto/getTransactions",
	GET_ALL_REDIRECTS = "/client-api/redirects/getAllRedirects",
	CREATE_REDIRECT = "/client-api/admin/redirects/createRedirect",
}
