export enum Chatroom {
	Newcomers = "Newcomers",
	English = "English",
	Sports = "Sports",
	Polish = "Polish",
	Russian = "Russian",
	Spanish = "Spanish",
	French = "French",
	Portuguese = "Portuguese",
	Turkish = "Turkish",
	Japanese = "Japanese",
	Hindi = "Hindi",
	Swedish = "Swedish",
	Finnish = "Finnish",
	Pinoy = "Pinoy",
	Balkan = "Balkan",
	Other = "Other",
	Prediction = "Prediction",
	Moderators = "Moderators",
}
