export enum CryptoNode {
	nodeBTC1 = "BTC - nodeBTC1",
	nodeBTC2 = "BTC - nodeBTC2",
	fireUSDT = "USDT - fireUSDT",
	fireXRP = "XRP - fireXRP",
	nodeLTC1 = "LTC - nodeLTC1",
	fireETH = "ETH - fireETH",
	fireSOL = "SOL - fireSOL",
	fireTRX = "TRX - fireTRX",
	fireTRX_USDT = "USDT_TRX - fireTRX_USDT",
	fireUSDC_ETH = "USDC_ETH - fireUSDC_ETH",
	fireUSDC_SOL = "USDC_SOL - fireUSDC_SOL",
	fireDOGE = "DOGE - fireDOGE",
	fireUSD1_SOL = "USD1_SOL - fireUSD1_SOL",
	fireUSDT_BSC = "USDT_BSC - fireUSDT_BSC",
	fireBNB = "BNB - fireBNB",
}
