export enum Cryptocurrency {
	Bitcoin = "Bitcoin",
	Litecoin = "Litecoin",
	Ethereum = "Ethereum",
	Tether = "TETHER",
	Tron = "TRON",
	Ripple = "Ripple",
	Doge = "Doge",
	Solana = "Solana",
	USDC = "USDC",
	USD1 = "USD1",
}

export enum CryptoTicker {
	BTC = "BTC",
	LTC = "LTC",
	ETH = "ETH",
	USDT = "USDT",
	USDC = "USDC",
	TRX = "TRX",
	XRP = "XRP",
	DOGE = "DOGE",
	SOL = "SOL",
	USD1 = "USD1",
	USDT_TRX = "USDT_TRX",
	USDT_TRON = "USDT_TRON",
	USDC_ETH = "USDC_ETH",
	USDC_SOL = "USDC_SOL",
	USD1_SOL = "USD1_SOL",
	USDT_BSC = "USDT_BSC",
}
