export enum Feature {
	MultiWallets = "MultiWallets",
	Altcoins = "altcoins",
	WelcomeBonus = "welcomeBonus",
	FreeRewards = "freerewards",
	Affiliates = "affiliates",
	ExternalGames = "external-games",
	KOTH = "koth",
	SteamLogin = "steamLogin",
	GmailLogin = "gmailLogin",
	PasswordReset = "passwordReset",
	LiveSupport = "liveSupport",
	Cashback = "cashback",
	WAXPEER = "WAXPEER",
	ReviewStreamerWd = "reviewStreamerWd",
	ReviewNewAccountFirstWd = "reviewNewAccountFirstWd",
	DICE = "DICE",
	PayopFailedToSuccessState = "payop_failed_to_success_state",
	Hub88Integration = "hub88-integration",
	SoftswissIntegration = "softswiss-integration",
	HacksawIntegration = "hacksaw-integration",
	OursIntegration = "ours-integration",
	CSGO = "CSGO",
	DOTA2 = "DOTA2",
	TF2 = "TF2",
	RUST = "RUST",
	HILO = "HILO",
}
