export enum TestUserRole {
	ANONYMOUS,
	REGULAR,
	SUPERADMIN,
	ADMIN_USER_INFO_ADMIN,
	ADMIN_CRYPTOSUPADMIN,
	ADMIN_SPORTS_BLOG_ADMIN,
	ADMIN_PROMOTIONS_ADMIN,
	EV_REWARDS_SYSTEM_SUPERADMIN_WITH_USER_INFO,
	CMS_SUPERADMIN,
}
