export enum TestTag {
	SMOKE = "@smoke",
	ORIGINALS = "@originals",
	CHAT = "@chat",
	VISUAL = "@visual",
	REWARDS = "@rewards",
	SPINS = "@spins",
	FREE_SPINS = "@free-spins",
	SEQUENTIAL = "@sequential",
	HOMEPAGE = "@homepage",
	GAME_PROVIDERS = "@game-providers",
	ADMIN_PANEL = "@admin-panel",
	KOTH = "@koth",
	MINES = "@mines",
	PLINKO = "@plinko",
	KENO = "@keno",
	USER_INFO = "@user-info",
	PROMO_CODES = "@promo-codes",
	V4 = "@v4",
	LOGIN = "@login",
	PLATFORM_BUG = "@platform-bug",
	ACCEPTANCE = "@acceptance",
}
