export enum ToastSubTitle {
	RESEND_EMAIL = "Click here to re-send your verification email.",
	CLAIMED_BONUS = "Successfully claimed 15% instant rakeback welcome bonus! Enjoy!",
	HIDEN_STATISTICS_DISABLED = "Hidden statistics mode disabled!",
	HIDEN_STATISTICS_ENABLED = "Hidden statistics mode enabled!",
	SENDING_OUT_FREESPINS = "Started sending out freespins, please don't click 'GIVE' button again until you see new notification.",
	CASINO_REWARD_GIVEN = "Casino reward given successfully!",
	SETTINGS_UPDATED = "Settings updated",
	SUCCESSFUL_UPLOAD = "Successful upload",
	UPLOAD_CSV_FILE = "Please upload a CSV file!",
	REFRESHED_STATE = "Refreshed state",
	AUTOBET_FINISHED = "Autobet finished!",
	PASSWORD_CHANGED = "You have successfully changed your password. Have fun and good luck!",
	CHANGE_CAMPAIGN_STATUS = "Successfully changed status for campaign",
	PROMO_CODE_REDEEMED = "Promo code has been redeemed.",
	PROMO_CODE_ERROR_MESSAGE = "Promo has ended or is inactive.",
	SUCCESSFULLY_FETCHED_TRANSACTIONS = "Successfully fetched transactions.",
	PROMOCODE_NOT_FOUND = "Nothing found!",
	PROMOTION_CREATED_SUCCESSFULLY = "Promotion created successfully",
	PROMOTION_UPDATED_SUCCESSFULLY = "Promotion updated successfully",
	PROMOTION_DELETED = "Promotion deleted",
	NOTIFICATION_SENT = "Notification sent successfully!",
	BALANCE_TOO_LOW = "Balance too low",
	VERIFICATION_PENDING = "Your request is being handled",
	FREE_SPINS_REVOKED = "Successfully revoked specified free spin.",
}
