export enum Unit {
	COINS = "COINS",
	BTC_SATOSHI = "BTC_SATOSHI",
	ETH_GWEI = "ETH_GWEI",
	LTC_LITOSHI = "LTC_LITOSHI",
	TRX_SUN = "TRX_SUN",
	XRP_DROP = "XRP_DROP",
	DOGE_SHIBE = "DOGE_SHIBE",
	SOL_LAMPORT = "SOL_LAMPORT",
}
