import {
	CRASH_GAME_PAGE_ENDPOINT,
	DICE_GAME_PAGE_ENDPOINT,
	HILO_GAME_PAGE_ENDPOINT,
	KENO_GAME_PAGE_ENDPOINT,
	MINES_GAME_PAGE_ENDPOINT,
	PLINKO_GAME_PAGE_ENDPOINT,
	ROULETTE_GAME_PAGE_ENDPOINT,
} from "./page-endpoints";

export const GameToEndpointMap: Record<string, string> = {
	Crash: CRASH_GAME_PAGE_ENDPOINT,
	Dice: DICE_GAME_PAGE_ENDPOINT,
	Roulette: ROULETTE_GAME_PAGE_ENDPOINT,
	Hilo: HILO_GAME_PAGE_ENDPOINT,
	Plinko: PLINKO_GAME_PAGE_ENDPOINT,
	Mines: MINES_GAME_PAGE_ENDPOINT,
	Keno: KENO_GAME_PAGE_ENDPOINT,
};
