export enum CustomRewardType {
	RELOAD = "reload",
	RELOADS = "Reloads",
	VIP = "vip",
	XP_CHALLENGE = "xp_challenge",
	XP_CHALLENGE_LABEL = "XP Challenge",
	KYC_VERIFICATION = "kyc_verification",
	KYC_VERIFICATION_LABEL = "KYC Verification",
	CASH = "cash",
	FREE_SPINS = "free spins",
	GIVEAWAY = "giveaway",
	DEPOSIT_BONUS = "deposit bonus",
	INSTANT_RAKEBACK = "instant rakeback",
	INSTANT_RAKEBACK_LABEL = "Instant_rakeback",
	ROYALTY_UP_LABEL = "Royalty_up",
	ROYALTY_UP = "royalty up",
	EV_REWARD = "ev_reward",
	EV_REWARD_LABEL = "ev reward",
	WEEKLY = "weekly",
	MONTHLY = "monthly",
	FREE_SPINS_PROMOTION = "Free_spins_promotion",
}
