export enum CampaignsColumns {
	Id = "id",
	Name = "name",
	Status = "status",
	PromoCode = "promo_code",
	PromoType = "promo_type",
	RewardAmount = "reward_amount",
	RewardCurrency = "reward_currency",
	ExpirationDate = "expiration_date",
	MaxRedemptions = "max_redemptions",
	RedemptionsCount = "redemptions_count",
	GameCode = "game_code",
	PrepaidUuid = "prepaid_uuid",
	FreeSpinsRounds = "free_spins_rounds",
	ReloadDays = "reload_days",
	AdminId = "admin_id",
	Created = "created",
	ModifiedDate = "modified_date",
}
