export enum DbTables {
	Users = "Users",
	Wallets = "Public.Wallets",
	Campaigns = "Promo_codes.Campaigns",
	CampaignRedemptions = "Promo_codes.Campaign_redemptions",
	CampaignRules = "Promo_codes.Campaign_rules",
	Settings = "Public.Settings",
	AmlInfo = "aml.info",
	AmlStatus = "aml.status",
	KothEvents = "koth.events",
	Promotions = "promotions.promotions",
	VipUsers = "public.vip_users",
	Rewards = "rewards.rewards",
	FreeSpinsPromotionsEventData = "rewards.free_spins_promotions_event_data",
}
