export enum DbTables {
	Users = "Users",
	Wallets = "Public.Wallets",
	Campaigns = "Promo_codes.Campaigns",
	CampaignRedemptions = "Promo_codes.Campaign_redemptions",
	CampaignRules = "Promo_codes.Campaign_rules",
	Settings = "Public.Settings",
	AmlInfo = "aml.info",
	AmlStatus = "aml.status",
	KycUserLevels = "aml.kyc_user_levels",
	KothEvents = "koth.events",
	Promotions = "promotions.promotions",
	VipUsers = "public.vip_users",
	Rewards = "rewards.rewards",
	ClaimHistory = "rewards.claim_history",
	FreeSpinsPromotionsEventData = "rewards.free_spins_promotions_event_data",
	GeoipHistory = "public.geoip_history",
	OtherAuditLog = "public.other_audit_log",
	AdminNotes = "public.admin_notes",
}
