export enum PromotionColumns {
	Id = "id",
	Title = "title",
	Subtitle = "subtitle",
	Description = "description",
	TermsAndConditions = "terms_and_conditions",
	ImageCover = "image_cover",
	ImageThumbnail = "image_thumbnail",
	HowToParticipate = "how_to_participate",
	RewardsInfo = "rewards_info",
	Priority = "priority",
	IsVisible = "is_visible",
	ButtonLink = "button_link",
	CustomUrl = "custom_url",
	Category = "category",
	SubCategory = "sub_category",
	CreatedByAdminId = "created_by_admin_id",
	UpdatedByAdminId = "updated_by_admin_id",
	StartDate = "start_date",
	ExpirationDate = "expiration_date",
	Created = "created",
	ModifiedDate = "modified_date",
}