export enum UsersColumns {
	Id = "id",
	Username = "username",
	Email = "email",
	Wagered = "wagered",
	Tags = "tags",
	UserClass = "userclass",
	TotalDeposited = "total_deposited",
	EmailVerified = "email_verified",
	XP = "xp",
	PHONE_NUMBER = "phone_number",
	PasswordHash = "password_hash",
	Image = "image",
	IsVip = "is_vip",
}
