export type UserDTO = {
	id: number;
	steamid: string | null;
	email: string;
	email_verified: boolean;
	image: string;
	email_consent: boolean;
	phone_number_verified: boolean;
	phone_number: string | null;
	username: string;
	userclass: string;
	net_profit: number;
	xp: number;
	tags: string;
	tradelink: string | null;
	steam_apikey: string | null;
	name_promotion: boolean;
	last_claimed: string | null;
	admin: boolean;
	moderator: boolean;
	twitter_user_id: string | null;
	total_deposited: number;
	muted_until: string | null;
	banned: boolean;
	banned_soft: boolean;
	steam_profile_private: boolean;
	created: string;
	totp_active: boolean;
	games_played: number;
	total_reward_amount_claimed: number;
	wagered: number;
	kyc_level: string | null;
	kyc_six_digits: string | null;
	kyc_six_digits_date: string | null;
	lvl1_status: string | null;
	lvl2_status: string | null;
	lvl3_status: string | null;
	used_affil_code: string | null;
	wager_req_end: string | null;
	wager_req_start: string | null;
	display_username: string;
	hidden_mode: boolean;
	hidden_statistics: boolean;
	self_exclusion_end: string | null;
	total_cashback_claimed: number;
	cashback_to_claim: number;
	marketing_rakeback_exp_date: string | null;
	telegram_id: string | null;
	telegram_username: string | null;
	telegram_pp: string | null;
	twitch_id: string | null;
	twitch_pp: string | null;
	twitch_username: string | null;
	discord_id: string | null;
	discord_pp: string | null;
	discord_username: string | null;
	surprise_cashback_claimable: number;
	weekly_cashback_claimable: number;
	weekly_cashback_totransfer: number;
	monthly_cashback_claimable: number;
	monthly_cashback_totransfer: number;
	rain_claimable_left: number;
	intercom_hmac_hash: string;
	wagered_surprise: number;
	vip_active: boolean;
	initial_locales: string;
	vault_enabled: boolean;
	vault_disabled_reason: string | null;
};

export type BasicInfoResponse = {
	user: UserDTO;
	required2faForLogin: boolean;
	featuresEnabled: string[];
	seonSessionId: string;
	eventImages: {
		logo: string | null;
		background: string | null;
	};
	telegramLoginBotData: string | null;
};
