import { PromotionStatuses } from "@enums/promotion-statuses";
import { PromotionType } from "@enums/promotion-types";
import { RandomDataSource } from "test-data/core/random-data-source";
import { PromoCodeScenario } from "test-data/interfaces/domain/promo-code-domain-interfaces";

export class PromoCodeDomainData {
	public readonly promoTypes: PromotionType[] = [
		PromotionType.CASH,
		PromotionType.CASH_RELOAD,
		PromotionType.FREE_SPINS,
	];
	public readonly finalStatuses: PromotionStatuses[] = [
		PromotionStatuses.ACTIVE,
		PromotionStatuses.FINISHED,
		PromotionStatuses.CANCELED,
	];

	public readonly campaignManagementScenarios: PromoCodeScenario[] =
		this.generateAllScenarios();

	private generateAllScenarios() {
		const scenarios: PromoCodeScenario[] = [];

		for (const promoType of this.promoTypes) {
			for (const status of this.finalStatuses) {
				scenarios.push({
					promoType: promoType,
					status: status,
					description: `${promoType} promo - ${status} campaign`,
				});
			}
		}

		return scenarios;
	}

	/**
	 * Builds a predefined promoCodesMap used in campaign management tests.
	 * Each entry combines a PromotionType and PromotionStatus with randomly
	 * generated promo code name and value.
	 *
	 * Example key: "CASH_ACTIVE" → { name: "auto_cash_active_xyz", value: "abc1234" }
	 *
	 * @param testDataRandom Random data generator instance used for code creation
	 * @returns Record<string, { name: string; value: string }>
	 */
	public buildPromoCodesMap(
		testDataRandom: RandomDataSource,
	): Record<string, { name: string; value: string }> {
		const promoCodesMap: Record<string, { name: string; value: string }> =
			{};
		const promoData = testDataRandom.data.generators.promoCampaignCodes;

		for (const { promoType, status } of this.campaignManagementScenarios) {
			const name = promoData.name(promoType, status);
			const value = promoData.codeValue();
			promoCodesMap[`${promoType}_${status}`] = { name, value };
		}

		return promoCodesMap;
	}

	/**
	 * Retrieves a specific promo code entry from the provided promoCodesMap
	 * based on the given promotion type and final status.
	 *
	 * The key is automatically normalized to uppercase to ensure consistent lookup
	 * (e.g. both "cash_active" and "CASH_ACTIVE" resolve to the same entry).
	 *
	 * @param promoCodesMap - Map generated by buildPromoCodesMap, containing all promo codes.
	 * @param promoType - The promotion type to look up (e.g. "CASH", "FREE_SPINS").
	 * @param finalStatus - The final campaign status to look up (e.g. "ACTIVE", "FINISHED").
	 * @returns The promo code object containing its name and value for the specified key.
	 */
	public getPromoCode(
		promoCodesMap: Record<string, { name: string; value: string }>,
		promoType: string,
		finalStatus: string,
	): { name: string; value: string } {
		const key = `${promoType.toUpperCase()}_${finalStatus.toUpperCase()}`;
		return promoCodesMap[key];
	}
}
