name: Detect and Run Modified Playwright Tests

on:
    workflow_call:
        secrets:
            JIRA_TOKEN:
                required: true
            JIRA_USERNAME:
                required: true
            XRAY_CLIENT_ID:
                required: true
            XRAY_CLIENT_SECRET:
                required: true
            SLACK_BOT_USER_OAUTH_TOKEN:
                required: true
            STEAM_USERNAME:
                required: true
            STEAM_PASSWORD:
                required: true
            GOOGLE_EMAIL:
                required: true
            GOOGLE_PASSWORD:
                required: true
            GOOGLE_AUTH_SECRET:
                required: true
            OXYLABS_USER:
                required: true
            OXYLABS_PASSWORD:
                required: true
            MAILINATOR_API_KEY:
                required: true
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_DEFAULT_REGION:
                required: true
            OAUTH2_JWT:
                required: true
            DB_HOST:
                required: true
            DB_USER:
                required: true
            DB_PASSWORD:
                required: true
            DB_NAME:
                required: true
            DB_PORT:
                required: true
            BITCOIN_RPC_HOST:
                required: true
            BITCOIN_RPC_PORT:
                required: true
            BITCOIN_RPC_USER:
                required: true
            BITCOIN_RPC_PASS:
                required: true
            FIREBLOCKS_API_KEY:
                required: true
            FIREBLOCKS_BASE_URL:
                required: true
            FIREBLOCKS_SECRET_KEY:
                required: true
            FIREBLOCKS_SECRET_KEY_PATH:
                required: true
            FIREBLOCKS_USDT_ASSET_ID:
                required: true
            FIREBLOCKS_VAULT_ID:
                required: true
            XRP_TESTNET_WALLET_SEED:
                required: true
            XRP_TESTNET_RPC_URL:
                required: true
            XRP_TESTNET_FAUCET_URL:
                required: true
            LITECOIN_RPC_PORT:
                required: true
            FIREBLOCKS_ETH_ASSET_ID:
                required: true
            FIREBLOCKS_SOL_ASSET_ID:
                required: true
            FIREBLOCKS_TRX_ASSET_ID:
                required: true
            FIREBLOCKS_USDT_TRX_ASSET_ID:
                required: true
            VERIFF_PUBLISHABLE_KEY:
                required: true
            VERIFF_PRIVATE_KEY:
                required: true
            VERIFF_USERNAME:
                required: true
            VERIFF_PASSWORD:
                required: true
            VERIFF_SECRET_2FA:
                required: true

concurrency:
    group: detect-modified-tests-${{ github.ref }}
    cancel-in-progress: true

env:
    CI: true
    BUILD_NUMBER: ${{ github.run_number }}
    BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    ENVIRONMENT_URL: ${{ vars.ENVIRONMENT_URL }}
    JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
    JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
    XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
    XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
    SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
    STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
    STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
    GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
    GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
    GOOGLE_AUTH_SECRET: ${{ secrets.GOOGLE_AUTH_SECRET }}
    OXYLABS_USER: ${{ secrets.OXYLABS_USER }}
    OXYLABS_PASSWORD: ${{ secrets.OXYLABS_PASSWORD }}
    MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: eu-west-2
    OAUTH2_JWT: ${{ secrets.OAUTH2_JWT }}
    DB_HOST: ${{ secrets.DB_HOST }}
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    DB_NAME: ${{ secrets.DB_NAME }}
    DB_PORT: ${{ secrets.DB_PORT }}
    BITCOIN_RPC_HOST: ${{ secrets.BITCOIN_RPC_HOST }}
    BITCOIN_RPC_PORT: ${{ secrets.BITCOIN_RPC_PORT }}
    BITCOIN_RPC_USER: ${{ secrets.BITCOIN_RPC_USER }}
    BITCOIN_RPC_PASS: ${{ secrets.BITCOIN_RPC_PASS }}
    FIREBLOCKS_API_KEY: ${{ secrets.FIREBLOCKS_API_KEY }}
    FIREBLOCKS_BASE_URL: ${{ secrets.FIREBLOCKS_BASE_URL }}
    FIREBLOCKS_SECRET_KEY: ${{ secrets.FIREBLOCKS_SECRET_KEY }}
    FIREBLOCKS_SECRET_KEY_PATH: ${{ secrets.FIREBLOCKS_SECRET_KEY_PATH }}
    FIREBLOCKS_USDT_ASSET_ID: ${{ secrets.FIREBLOCKS_USDT_ASSET_ID }}
    FIREBLOCKS_VAULT_ID: ${{ secrets.FIREBLOCKS_VAULT_ID }}
    XRP_TESTNET_WALLET_SEED: ${{ secrets.XRP_TESTNET_WALLET_SEED }}
    XRP_TESTNET_RPC_URL: ${{ secrets.XRP_TESTNET_RPC_URL }}
    XRP_TESTNET_FAUCET_URL: ${{ secrets.XRP_TESTNET_FAUCET_URL }}
    LITECOIN_RPC_PORT: ${{ secrets.LITECOIN_RPC_PORT }}
    FIREBLOCKS_ETH_ASSET_ID: ${{ secrets.FIREBLOCKS_ETH_ASSET_ID }}
    FIREBLOCKS_SOL_ASSET_ID: ${{ secrets.FIREBLOCKS_SOL_ASSET_ID }}
    FIREBLOCKS_TRX_ASSET_ID: ${{ secrets.FIREBLOCKS_TRX_ASSET_ID }}
    FIREBLOCKS_USDT_TRX_ASSET_ID: ${{ secrets.FIREBLOCKS_USDT_TRX_ASSET_ID }}
    VERIFF_PUBLISHABLE_KEY: ${{ secrets.VERIFF_PUBLISHABLE_KEY }}
    VERIFF_PRIVATE_KEY: ${{ secrets.VERIFF_PRIVATE_KEY }}
    VERIFF_USERNAME: ${{ secrets.VERIFF_USERNAME }}
    VERIFF_PASSWORD: ${{ secrets.VERIFF_PASSWORD }}
    VERIFF_SECRET_2FA: ${{ secrets.VERIFF_SECRET_2FA }}
    FIREBLOCKS_USDC_ETH_ASSET_ID: ${{ vars.FIREBLOCKS_USDC_ETH_ASSET_ID }}

jobs:
    detect-new-modified-tests:
        runs-on: self-hosted-dind-fulltest
        timeout-minutes: 30
        environment: staging
        outputs:
            run_tests: ${{ steps.detect.outputs.run_tests }}
            test_files: ${{ steps.detect.outputs.test_files }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Fetch All Branches to Ensure Base Exists
              run: |
                  git remote -v  
                  git fetch --all --prune  
                  git branch -r

            - name: Detect newly added and modified test files
              id: detect
              run: |
                  git fetch origin master --depth=1  

                  BASE_COMMIT=origin/master
                  echo "Comparing against base commit: $BASE_COMMIT"

                  echo "=== Show file differences ==="
                  git diff --name-status $BASE_COMMIT HEAD

                  NEW_OR_MODIFIED_TESTS=$(git diff --name-only --diff-filter=AM $BASE_COMMIT HEAD | grep -E "tests/.*\.spec\.ts$" || true)

                  if [[ -z "$NEW_OR_MODIFIED_TESTS" ]]; then
                      echo "No new or modified test files found."
                      echo "run_tests=false" >> $GITHUB_OUTPUT
                  else
                      echo "Detected new/modified test files:"
                      echo "$NEW_OR_MODIFIED_TESTS"
                      TEST_FILES=$(echo "$NEW_OR_MODIFIED_TESTS" | xargs)
                      echo "test_files=$TEST_FILES" >> $GITHUB_OUTPUT
                      echo "run_tests=true" >> $GITHUB_OUTPUT
                  fi

    run-new-modified-tests:
        needs: detect-new-modified-tests
        if: needs.detect-new-modified-tests.outputs.run_tests == 'true'
        runs-on: self-hosted-dind-playwright
        timeout-minutes: 60
        environment: staging

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install Node.js dependencies
              run: |
                  if ! command -v yarn &>/dev/null; then
                    npm install -g yarn
                  fi
                  yarn install --immutable --immutable-cache --check-cache

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y git curl unzip gh
                  if ! command -v aws &> /dev/null; then
                      echo "AWS CLI not found. Installing..."
                      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                      unzip awscliv2.zip
                      sudo ./aws/install
                  else
                      echo "AWS CLI is already installed. Skipping installation."
                  fi

            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps

            - name: Run New or Modified Tests
              run: |
                  echo "Running tests: ${{ needs.detect-new-modified-tests.outputs.test_files }}"
                  yarn playwright test ${{ needs.detect-new-modified-tests.outputs.test_files }} --repeat-each=5 --workers=10 --retries=0 --grep-invert @v4

            - name: Upload Playwright report to S3 and generate report url
              if: always()
              run: |
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  S3_KEY_PREFIX="playwright-reports/${{ github.run_id }}-${TIMESTAMP}"
                  ./scripts/upload_to_s3.sh playwright-report gamdom-prod-qa-reporting $S3_KEY_PREFIX
