name: Playwright E2E Tests

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to run tests against"
                type: string
                required: true
            tag:
                description: "Tag scope"
                required: true
                default: "all"
                type: choice
                options:
                    - all
                    - smoke
                    - visual
                    - originals
            custom_options:
                description: "Custom command-line options"
                type: string
                required: false
            run_game_providers_tests:
                description: "Run Game Providers tests"
                type: choice
                required: true
                options:
                    - Run Game Providers tests
                    - Do Not Run Game Providers tests

    workflow_call:
        secrets:
            JIRA_TOKEN:
                required: true
                description: "Jira Token"
            JIRA_USERNAME:
                required: true
                description: "Jira Username"
            XRAY_CLIENT_ID:
                required: true
                description: "X-Ray Client ID"
            XRAY_CLIENT_SECRET:
                required: true
                description: "X-Ray Client Secret"
            SLACK_BOT_USER_OAUTH_TOKEN:
                required: true
                description: "Slack Bot User Oauth Token"
            STEAM_USERNAME:
                required: true
                description: "Steam authentication username"
            STEAM_PASSWORD:
                required: true
                description: "Steam authentication password"
            GOOGLE_EMAIL:
                required: true
                description: "Google authentication email"
            GOOGLE_PASSWORD:
                required: true
                description: "Google authentication password"
            GOOGLE_AUTH_SECRET:
                required: true
                description: "Google authentication QR code secret"
            OXYLABS_USER:
                required: true
                description: "Proxy oxylabs authentication username"
            OXYLABS_PASSWORD:
                required: true
                description: "Proxy oxylabs authentication password"
            MAILINATOR_API_KEY:
                required: true
                description: "Mailinator authentication"
            AWS_ACCESS_KEY_ID:
                required: true
                description: AWS Access key ID
            AWS_SECRET_ACCESS_KEY:
                required: true
                description: AWS Secret Access key
            AWS_DEFAULT_REGION:
                required: true
                description: AWS Default region

    schedule:
        - cron: "0 2 * * *"

concurrency:
    group: playwright-e2e-${{ github.ref }}
    cancel-in-progress: false

jobs:
    tests:
        timeout-minutes: 600
        runs-on: self-hosted-dind
        strategy:
            fail-fast: false
            matrix:
                shard: [1]

        env:
            CI: true
            BUILD_NUMBER: ${{ github.run_number }}
            BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
            XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
            GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
            GOOGLE_AUTH_SECRET: ${{ secrets.GOOGLE_AUTH_SECRET }}
            OXYLABS_USER: ${{ secrets.OXYLABS_USER }}
            OXYLABS_PASSWORD: ${{ secrets.OXYLABS_PASSWORD }}
            MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: eu-west-2
            ENVIRONMENT_URL: ${{ inputs.environment == '' && vars.ENVIRONMENT_URL || inputs.environment }}
            SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
            TAG: ${{ inputs.tag == '' && 'smoke' || inputs.tag }}
            SHARD_OPTION: --shard ${{ matrix.shard }}/${{ strategy.job-total }}
            GREP_GAME_PROVIDERS_TESTS: --grep @game-providers
            INVERT_GAME_PROVIDERS_TESTS: --grep-invert @game-providers
            CUSTOM_OPTIONS: ${{ inputs.custom_options }}

        steps:
            - name: Validation For Environment URL
              run: |
                  echo "Validating that Environment URL is valid format (and does not end with slash)"
                  echo $ENVIRONMENT_URL | grep -E '^(http|https)://[a-zA-Z0-9./?=_-]*[^/]$'

            - name: Checkout E2E tests repository
              uses: actions/checkout@v4

            - name: Setup Node modules
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y git curl unzip gh
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  unzip awscliv2.zip
                  sudo ./aws/install

            - name: Install Node.js dependencies
              run: |
                  if ! command -v yarn &>/dev/null; then
                    npm install -g yarn
                  fi
                  yarn install

            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache

            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps

            - name: Run Playwright tests (Cron trigger)
              if: ${{ github.event_name == 'schedule' }}
              run: yarn playwright test $SHARD_OPTION

            - name: Run Playwright tests (Manual trigger)
              if: ${{ github.event_name != 'schedule' }}
              run: |
                  if [ "$TAG" == "all" ]; then
                    echo "Running all tests ${CUSTOM_OPTIONS:+with custom options: $CUSTOM_OPTIONS}"
                    yarn playwright test $CUSTOM_OPTIONS $INVERT_GAME_PROVIDERS_TESTS $SHARD_OPTION 
                  else
                    echo "Running tests with tag: "@$TAG" ${CUSTOM_OPTIONS:+and custom options: $CUSTOM_OPTIONS}"
                    yarn playwright test --grep "@$TAG" $CUSTOM_OPTIONS $INVERT_GAME_PROVIDERS_TESTS $SHARD_OPTION 
                  fi

            - name: Upload blob report to GitHub Actions Artifacts
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: "all-blob-reports-1-${{ github.run_id }}-${{ matrix.shard }}"
                  path: ./blob-report
                  retention-days: 7

            - name: Run Playwright tests - Game Providers
              if: ${{ github.event_name == 'schedule' || inputs.run_game_providers_tests == 'Run Game Providers tests' }}
              run: |
                  echo "Running all tests related to Game Providers"
                  yarn playwright test $GREP_GAME_PROVIDERS_TESTS

            - name: Upload blob report to GitHub Actions Artifacts 2
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: "all-blob-reports-2-${{ github.run_id }}-${{ matrix.shard }}"
                  path: ./blob-report
                  retention-days: 7

            - name: Download blob reports from GitHub Actions Artifacts
              if: always()
              uses: actions/download-artifact@v4
              with:
                  path: ./blob-report
                  pattern: all-blob-reports-*
                  merge-multiple: true

            - name: Merge all blob reports into HTML and json
              if: always()
              run: npx playwright merge-reports --reporter json,html ./blob-report > e2e-results.json

            - name: Upload Playwright report to S3 and generate report url
              if: always()
              run: |
                  # Create a unique directory name using the GitHub run ID and timestamp
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  S3_KEY_PREFIX="playwright-reports/${{ github.run_id }}-${TIMESTAMP}"

                  # Call the upload script with the required parameters
                  ./scripts/upload_to_s3.sh playwright-report gamdom-prod-qa-reporting $S3_KEY_PREFIX

            - name: Use REPORT_URL in another step
              run: |
                  echo "The report is available at: $REPORT_URL"
              env:
                  REPORT_URL: ${{ env.REPORT_URL }}

            - name: Send report to Slack using CLI
              if: always()
              env:
                  SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
                  SLACK_CHANNEL: playwright-e2e-reporting
                  REPORT_URL: ${{ env.REPORT_URL }}
                  TEST_EXECUTION_ID: ${{ env.TEST_EXECUTION_ID }}
                  BRANCH_NAME: ${{ github.event_name == 'schedule' && 'master' || github.head_ref || github.ref_name }}
                  USER_NAME: ${{ github.event_name == 'schedule' && 'scheduled run' || github.actor }}
                  PULL_REQUEST_URL: ${{ github.event_name == 'schedule' && 'No PR created' || github.event.pull_request.html_url || 'No PR created' }}
              run: npx playwright-slack-report --config="${GITHUB_WORKSPACE}/core/reporters/slack-reporter-cli/slack-message-config-cli.json" --json-results="${GITHUB_WORKSPACE}/e2e-results.json"

            - name: Create PR comment with report url
              if: ${{ always() && github.event_name == 'pull_request' }}
              run: |
                  COMMENT=":world_map: Playwright report available [here]($REPORT_URL)"
                  echo $COMMENT
                  gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
