name: Playwright Visual Tests - Archive Linux Images
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to run tests against"
                type: string
                required: true
            tag:
                description: "Tag scope"
                required: true
                default: "visual"
                type: choice
                options:
                    - visual
            custom_options:
                description: "Custom command-line options"
                type: string
                required: false

jobs:
    visual-tests-images:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            CI: ""
            BUILD_NUMBER: ${{ github.run_number }}
            BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
            CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
            XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}

            ENVIRONMENT_URL: ${{ inputs.environment == '' && vars.ENVIRONMENT_URL || inputs.environment }}
            SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
            TAG: ${{ inputs.tag == '' && 'visual' || inputs.tag }}

        steps:
            - name: Validation For Environment URL
              run: |
                  echo "Validating that Environment URL is valid format (and does not end with slash)"
                  echo $ENVIRONMENT_URL | grep -E '^(http|https)://[a-zA-Z0-9./?=_-]*[^/]$'
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache
            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps
            - name: Run Playwright tests
              run: yarn playwright test --grep "$TAG" ${{ inputs.custom_options }}
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
            - name: Upload visual base images
              uses: actions/upload-artifact@v4
              with:
                  name: base-images
                  path: tests/**/*-snapshots
                  retention-days: 5
