name: Playwright E2E Tests
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to run tests against"
                type: string
                required: true
            tag:
                description: "Tag scope"
                required: true
                default: "all"
                type: choice
                options:
                    - all
                    - smoke
                    - visual

    workflow_call:
        secrets:
            CF_ACCESS_CLIENT_ID:
                required: true
                description: "CloudFlare Access Client ID"
            CF_ACCESS_CLIENT_SECRET:
                required: true
                description: "CloudFlare Access Client Secret"
            JIRA_TOKEN:
                required: true
                description: "Jira Token"
            JIRA_USERNAME:
                required: true
                description: "Jira Username"
            XRAY_CLIENT_ID:
                required: true
                description: "X-Ray Client ID"
            XRAY_CLIENT_SECRET:
                required: true
                description: "X-Ray Client Secret"
            SLACK_BOT_USER_OAUTH_TOKEN:
                required: true
                description: "Slack Bot User Oauth Token"
            STEAM_USERNAME:
                required: true
                description: "Steam authentication username"
            STEAM_PASSWORD:
                required: true
                description: "Steam authentication password"

jobs:
    tests:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            CI: true
            BUILD_NUMBER: ${{ github.run_number }}
            BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
            CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
            XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

            ENVIRONMENT_URL: ${{ inputs.environment == '' && vars.ENVIRONMENT_URL || inputs.environment }}
            SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
            TAG: ${{ inputs.tag == '' && 'smoke' || inputs.tag }}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache
            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps
            - name: Run Playwright tests
              run: yarn playwright test ${{ inputs.tag != 'all' && '--grep "$TAG"' || '' }}
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
