name: Playwright Visual Tests - CI Images

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to run tests against"
                type: string
                required: true
            tag:
                description: "Tag scope"
                required: true
                default: "visual"
                type: choice
                options:
                    - visual
            custom_options:
                description: "Custom command-line options"
                type: string
                required: false

concurrency:
    group: visual-tests-${{ github.ref }}
    cancel-in-progress: false

permissions:
    contents: write
    pull-requests: write
    actions: write

jobs:
    visual-tests-images:
        timeout-minutes: 60
        runs-on: ubuntu-latest

        env:
            CI: ""
            BUILD_NUMBER: ${{ github.run_number }}
            BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
            XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
            GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
            GOOGLE_AUTH_SECRET: ${{ secrets.GOOGLE_AUTH_SECRET }}
            MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
            ENVIRONMENT_URL: ${{ inputs.environment == '' && vars.ENVIRONMENT_URL || inputs.environment }}
            SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
            TAG: ${{ inputs.tag == '' && 'visual' || inputs.tag }}

        steps:
            - name: Validation For Environment URL
              run: |
                  echo "Validating that Environment URL is valid format (and does not end with slash)"
                  echo $ENVIRONMENT_URL | grep -E '^(http|https)://[a-zA-Z0-9./?=_-]*[^/]$'

            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache

            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps

            - name: Run Playwright tests with snapshot update
              run: yarn playwright test --grep "$TAG" --update-snapshots ${{ inputs.custom_options }}

            - name: Configure git for Pull Request update
              run: |
                  git config --global user.name 'IvStGamdom'
                  git config --global user.email 'ivaylo@teamgamdom.com'

            - name: Commit and push updated snapshots
              run: |
                  git checkout -- keystore.json
                  git add .
                  git commit -m "Update visual snapshots for CI"
                  git push origin ${{ github.event.pull_request.head.ref }}
              if: success()

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
