name: Premerge checks
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    workflow_dispatch:

concurrency:
    group: premerge-${{ github.ref }}
    cancel-in-progress: false

jobs:
    premerge-checks:
        runs-on: ubuntu-latest
        env:
            BUILD_NUMBER: ${{ github.run_number }}
            BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache
            - name: ESLint (Standard and Playwright)
              run: yarn lint
              env:
                  PRETTIER_CHECK: 1
                  NODE_OPTIONS: "--max_old_space_size=8192"
    tests-run:
        uses: ./.github/workflows/playwright.yml
        secrets:
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
            XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
            GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
            GOOGLE_AUTH_SECRET: ${{ secrets.GOOGLE_AUTH_SECRET }}
            MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: eu-west-2
            SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
        needs: premerge-checks
