name: Playwright E2E Tests Pull Request Checks

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

concurrency:
    group: premerge-${{ github.ref }}
    cancel-in-progress: false

jobs:
    premerge-checks:
        runs-on: self-hosted-dind-playwright
        env:
            BUILD_NUMBER: ${{ github.run_number }}
            BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install Node.js dependencies
              run: |
                  if ! command -v yarn &>/dev/null; then
                    npm install -g yarn
                  fi
                  yarn install

            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache

            - name: ESLint (Standard and Playwright)
              run: yarn lint
              env:
                  PRETTIER_CHECK: 1
                  NODE_OPTIONS: "--max_old_space_size=8192"

            - name: Check for missing @step decorators
              run: yarn lint:step-decorators

    detect-tests:
        needs: premerge-checks
        if: always()
        uses: ./.github/workflows/detect-modified-tests.yml
        secrets:
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
            XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
            SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
            GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
            GOOGLE_AUTH_SECRET: ${{ secrets.GOOGLE_AUTH_SECRET }}
            OXYLABS_USER: ${{ secrets.OXYLABS_USER }}
            OXYLABS_PASSWORD: ${{ secrets.OXYLABS_PASSWORD }}
            MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            OAUTH2_JWT: ${{ secrets.OAUTH2_JWT }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_PORT: ${{ secrets.DB_PORT }}
            BITCOIN_RPC_HOST: ${{ secrets.BITCOIN_RPC_HOST }}
            BITCOIN_RPC_PORT: ${{ secrets.BITCOIN_RPC_PORT }}
            BITCOIN_RPC_USER: ${{ secrets.BITCOIN_RPC_USER }}
            BITCOIN_RPC_PASS: ${{ secrets.BITCOIN_RPC_PASS }}
            FIREBLOCKS_API_KEY: ${{ secrets.FIREBLOCKS_API_KEY }}
            FIREBLOCKS_BASE_URL: ${{ secrets.FIREBLOCKS_BASE_URL }}
            FIREBLOCKS_SECRET_KEY: ${{ secrets.FIREBLOCKS_SECRET_KEY }}
            FIREBLOCKS_SECRET_KEY_PATH: ${{ secrets.FIREBLOCKS_SECRET_KEY_PATH }}
            FIREBLOCKS_USDT_ASSET_ID: ${{ secrets.FIREBLOCKS_USDT_ASSET_ID }}
            FIREBLOCKS_VAULT_ID: ${{ secrets.FIREBLOCKS_VAULT_ID }}
            XRP_TESTNET_WALLET_SEED: ${{ secrets.XRP_TESTNET_WALLET_SEED }}
            XRP_TESTNET_RPC_URL: ${{ secrets.XRP_TESTNET_RPC_URL }}
            XRP_TESTNET_FAUCET_URL: ${{ secrets.XRP_TESTNET_FAUCET_URL }}

    tests-run:
        needs: detect-tests
        if: always()
        uses: ./.github/workflows/playwright.yml
        secrets:
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
            XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
            GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
            GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
            GOOGLE_AUTH_SECRET: ${{ secrets.GOOGLE_AUTH_SECRET }}
            OXYLABS_USER: ${{ secrets.OXYLABS_USER }}
            OXYLABS_PASSWORD: ${{ secrets.OXYLABS_PASSWORD }}
            MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
            OAUTH2_JWT: ${{ secrets.OAUTH2_JWT }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_PORT: ${{ secrets.DB_PORT }}
            BITCOIN_RPC_HOST: ${{ secrets.BITCOIN_RPC_HOST }}
            BITCOIN_RPC_PORT: ${{ secrets.BITCOIN_RPC_PORT }}
            BITCOIN_RPC_USER: ${{ secrets.BITCOIN_RPC_USER }}
            BITCOIN_RPC_PASS: ${{ secrets.BITCOIN_RPC_PASS }}
            FIREBLOCKS_API_KEY: ${{ secrets.FIREBLOCKS_API_KEY }}
            FIREBLOCKS_BASE_URL: ${{ secrets.FIREBLOCKS_BASE_URL }}
            FIREBLOCKS_SECRET_KEY: ${{ secrets.FIREBLOCKS_SECRET_KEY }}
            FIREBLOCKS_SECRET_KEY_PATH: ${{ secrets.FIREBLOCKS_SECRET_KEY_PATH }}
            FIREBLOCKS_USDT_ASSET_ID: ${{ secrets.FIREBLOCKS_USDT_ASSET_ID }}
            FIREBLOCKS_VAULT_ID: ${{ secrets.FIREBLOCKS_VAULT_ID }}
            XRP_TESTNET_WALLET_SEED: ${{ secrets.XRP_TESTNET_WALLET_SEED }}
            XRP_TESTNET_RPC_URL: ${{ secrets.XRP_TESTNET_RPC_URL }}
            XRP_TESTNET_FAUCET_URL: ${{ secrets.XRP_TESTNET_FAUCET_URL }}
