name: Premerge checks
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    premerge-checks:
        runs-on: ubuntu-latest
        env:
            BUILD_NUMBER: ${{ github.run_number }}
            BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache
            - name: ESLint (Standard and Playwright)
              run: yarn lint
              env:
                  PRETTIER_CHECK: 1
                  NODE_OPTIONS: "--max_old_space_size=8192"
    tests-run:
        uses: ./.github/workflows/playwright.yml
        secrets:
            CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
            CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
            XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
            ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }}
            SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
        needs: premerge-checks
