name: Trigger Expired Ban Auto-Lock

on:
    workflow_dispatch:

jobs:
    run-expired-ban-auto-lock:
        runs-on: self-hosted-k8s
        timeout-minutes: 30
        steps:
            - name: Configure kubeconfig
              run: |
                  echo "{{ secrets.KUBECONFIG_STG_OVH }}" > .kubeconfig
                  set -xeuo pipefail
                  chmod 600 .kubeconfig
                  export KUBECONFIG=.kubeconfig

            - name: Find pod
              id: pod
              run: |
                  POD=$(kubectl get pod \
                    -n staging \
                    -l "app.kubernetes.io/instance=fixed-e2e-release" \
                    --no-headers | grep "app" | awk '{print $1}')

                  if [ -z "$POD" ]; then
                    echo "No app pod found"
                    exit 1
                  fi

                  echo "pod_name=${POD}" >> "$GITHUB_OUTPUT"
                  echo "Found pod: ${POD}"

            - name: Run script
              run: |
                  kubectl exec ${{ steps.pod.outputs.pod_name }} \
                    -n staging \
                    -- yarn auto-lock-expired-bans
